export const navigations = [
  {
    id: 'dashboard',
    title: 'Dashboard',
    path: '/',
  },
  {
    id: 'pools',
    title: 'Pools',
    path: '/pools',
  },
  {
    id: 'tokens',
    title: 'Tokens',
    path: '/tokens',
  },
]

export const networks = [
  {
    id: 'eth',
    title: 'Ethereum',
    short_name: 'ETH',
    chain_id: 1,
    info_url: 'https://ethereum.org',
    currency: {
      name: 'Ether',
      symbol: 'ETH',
      decimals: 18,
    },
    explorer: {
      name: 'Etherscan',
      url: 'https://etherscan.io',
      block_path: '/block/{block}',
      address_path: '/address/{address}',
      contract_path: '/token/{address}',
      transaction_path: '/tx/{tx}',
    },
    gas: 'https://www.gasnow.org/api/v3/gas/price',
  },
  {
    id: 'bsc',
    title: 'Binance Smart Chain',
    short_name: 'BSC',
    chain_id: 56,
    info_url: 'https://www.binance.org',
    currency: {
      name: 'Binance Chain Native Token',
      symbol: 'BNB',
      decimals: 18,
    },
    explorer: {
      name: 'BscScan',
      url: 'https://bscscan.com',
      block_path: '/block/{block}',
      address_path: '/address/{address}',
      contract_path: '/token/{address}',
      transaction_path: '/tx/{tx}',
    },
  },
  {
    id: 'matic',
    title: 'Polygon',
    short_name: 'MATIC',
    chain_id: 137,
    info_url: 'https://polygon.technology',
    currency: {
      name: 'Matic',
      symbol: 'MATIC',
      decimals: 18,
    },
    explorer: {
      name: 'PolygonScan',
      url: 'https://polygonscan.com',
      block_path: '/block/{block}',
      address_path: '/address/{address}',
      contract_path: '/token/{address}',
      transaction_path: '/tx/{tx}',
    },
    gas: 'https://gasstation-mainnet.matic.network',
  },
  {
    id: 'avax',
    title: 'Avalanche',
    short_name: 'AVAX',
    chain_id: 43114,
    info_url: 'https://www.avax.network',
    currency: {
      name: 'Avalanche',
      symbol: 'AVAX',
      decimals: 18,
    },
    explorer: {
      name: 'AVASCAN',
      url: 'https://avascan.info/blockchain/c',
      block_path: '/block/{block}',
      address_path: '/address/{address}',
      contract_path: '/token/{address}',
      transaction_path: '/tx/{tx}',
    },
  },
  {
    id: 'arb',
    title: 'Arbitrum',
    short_name: 'ARB',
    chain_id: 42161,
    info_url: 'https://bridge.arbitrum.io/',
    currency: {
      name: 'Arbitrum Ether',
      symbol: 'tETH',
      decimals: 18,
    },
    explorer: {
      name: 'ARBISCAN',
      url: 'https://arbiscan.io',
      block_path: '/block/{block}',
      address_path: '/address/{address}',
      contract_path: '/token/{address}',
      transaction_path: '/tx/{tx}',
    },
  },
  {
    id: 'xdai',
    title: 'xDAI Chain',
    short_name: 'XDAI',
    chain_id: 100,
    info_url: 'https://forum.poa.network/c/xdai-chain',
    currency: {
      name: 'xDAI',
      symbol: 'xDAI',
      decimals: 18,
    },
    explorer: {
      name: 'BlockScout',
      url: 'https://blockscout.com/xdai/mainnet',
      block_path: '/block/{block}',
      address_path: '/address/{address}',
      contract_path: '/token/{address}',
      transaction_path: '/tx/{tx}',
    },
  },
  {
    id: 'ftm',
    title: 'Fantom',
    short_name: 'FTM',
    chain_id: 250,
    info_url: 'https://fantom.foundation',
    currency: {
      name: 'Fantom',
      symbol: 'FTM',
      decimals: 18,
    },
    explorer: {
      name: 'FTMScan',
      url: 'https://ftmscan.com',
      block_path: '/block/{block}',
      address_path: '/address/{address}',
      contract_path: '/token/{address}',
      transaction_path: '/tx/{tx}',
    },
  },
  {
    id: 'heco',
    title: 'Huobi ECO Chain',
    short_name: 'HECO',
    chain_id: 128,
    info_url: 'https://www.hecochain.com',
    currency: {
      name: 'Huobi ECO Chain Native Token',
      symbol: 'HT',
      decimals: 18,
    },
    explorer: {
      name: 'HecoInfo',
      url: 'https://hecoinfo.com',
      block_path: '/block/{block}',
      address_path: '/address/{address}',
      contract_path: '/token/{address}',
      transaction_path: '/tx/{tx}',
    },
  },
  {
    id: 'mbase',
    title: 'Moonbase Alpha',
    short_name: 'MBASE',
    chain_id: 1287,
    info_url: 'https://moonbeam.network',
    currency: {
      name: 'Dev',
      symbol: 'DEV',
      decimals: 18,
    },
    explorer: {
      name: 'SUBSCAN',
      url: 'https://moonbase.subscan.io',
      block_path: '/block/{block}',
      address_path: '/account/{address}',
      contract_path: '/account/{address}',
      transaction_path: '/extrinsic/{tx}',
    },
  },
].map(network => { return { ...network, url: `/${network.id}`, icon: `/logos/chains/${network.id}.png` } })